version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      WP_ENVIRONMENT_TYPE: development

  db:
    image: mysql
    # This is a UNSAFE configuration not intended to run in a production environment
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined

  adminer:
    image: adminer
    restart: always
    ports:
      - "8001:8080"
    depends_on:
      - db
